from __future__ import annotations


CURRENT_SQUADS = {
    "Chennai Super Kings": {
        "Batters": [
            "Ruturaj Gaikwad",
            "MS Dhoni",
            "Sanju Samson",
            "Dewald Brevis",
            "Ayush Mhatre",
            "Kartik Sharma",
            "Sarfaraz Khan",
            "Urvil Patel",
        ],
        "All-rounders": [
            "Jamie Overton",
            "Ramakrishna Ghosh",
            "Prashant Veer",
            "Matthew William Short",
            "Aman Khan",
            "Zak Foulkes",
            "Shivam Dube",
        ],
        "Bowlers": [
            "Khaleel Ahmed",
            "Noor Ahmad",
            "Anshul Kamboj",
            "Mukesh Choudhary",
            "Shreyas Gopal",
            "Gurjapneet Singh",
            "Akeal Hosein",
            "Matt Henry",
            "Rahul Chahar",
            "Spencer Johnson",
        ],
    },
    "Delhi Capitals": {
        "Batters": [
            "KL Rahul",
            "Karun Nair",
            "David Miller",
            "Ben Duckett",
            "Pathum Nissanka",
            "Sahil Parakh",
            "Prithvi Shaw",
            "Abishek Porel",
            "Tristan Stubbs",
        ],
        "All-rounders": [
            "Axar Patel",
            "Sameer Rizvi",
            "Ashutosh Sharma",
            "Vipraj Nigam",
            "Ajay Mandal",
            "Tripurana Vijay",
            "Madhav Tiwari",
            "Nitish Rana",
        ],
        "Bowlers": [
            "Mitchell Starc",
            "T. Natarajan",
            "Mukesh Kumar",
            "Dushmantha Chameera",
            "Auqib Nabi",
            "Lungisani Ngidi",
            "Kyle Jamieson",
            "Kuldeep Yadav",
        ],
    },
    "Gujarat Titans": {
        "Batters": [
            "Shubman Gill",
            "Jos Buttler",
            "Kumar Kushagra",
            "Anuj Rawat",
            "Connor Esterhuizen",
            "Glenn Phillips",
            "Sai Sudharsan",
        ],
        "All-rounders": [
            "Nishant Sindhu",
            "Washington Sundar",
            "Mohd. Arshad Khan",
            "Sai Kishore",
            "Jayant Yadav",
            "Jason Holder",
            "Rahul Tewatia",
            "Shahrukh Khan",
        ],
        "Bowlers": [
            "Kagiso Rabada",
            "Mohammed Siraj",
            "Prasidh Krishna",
            "Manav Suthar",
            "Gurnoor Singh Brar",
            "Ishant Sharma",
            "Ashok Sharma",
            "Luke Wood",
            "Kulwant Khejroliya",
            "Rashid Khan",
        ],
    },
    "Kolkata Knight Riders": {
        "Batters": [
            "Ajinkya Rahane",
            "Rinku Singh",
            "Angkrish Raghuvanshi",
            "Manish Pandey",
            "Finn Allen",
            "Tejasvi Singh",
            "Rahul Tripathi",
            "Tim Seifert",
            "Rovman Powell",
        ],
        "All-rounders": [
            "Anukul Roy",
            "Cameron Green",
            "Sarthak Ranjan",
            "Daksh Kamra",
            "Rachin Ravindra",
            "Ramandeep Singh",
            "Sunil Narine",
        ],
        "Bowlers": [
            "Blessing Muzarabani",
            "Vaibhav Arora",
            "Matheesha Pathirana",
            "Kartik Tyagi",
            "Prashant Solanki",
            "Saurabh Dubey",
            "Navdeep Saini",
            "Umran Malik",
            "Varun Chakaravarthy",
        ],
    },
    "Lucknow Super Giants": {
        "Batters": [
            "Rishabh Pant",
            "Aiden Markram",
            "Himmat Singh",
            "Matthew Breetzke",
            "Mukul Choudhary",
            "Akshat Raghuwanshi",
            "Josh Inglis",
            "Nicholas Pooran",
        ],
        "All-rounders": [
            "Mitchell Marsh",
            "Abdul Samad",
            "Shahbaz Ahamad",
            "Arshin Kulkarni",
            "Ayush Badoni",
        ],
        "Bowlers": [
            "Mohammad Shami",
            "Avesh Khan",
            "M. Siddharth",
            "Digvesh Singh",
            "Akash Singh",
            "Prince Yadav",
            "Arjun Tendulkar",
            "Anrich Nortje",
            "Naman Tiwari",
            "George Linde",
            "Mayank Yadav",
            "Mohsin Khan",
        ],
    },
    "Mumbai Indians": {
        "Batters": [
            "Rohit Sharma",
            "Surya Kumar Yadav",
            "Robin Minz",
            "Sherfane Rutherford",
            "Ryan Rickelton",
            "Quinton de Kock",
            "Danish Malewar",
            "Krish Bhagat",
            "N. Tilak Varma",
        ],
        "All-rounders": [
            "Hardik Pandya",
            "Naman Dhir",
            "Mitchell Santner",
            "Raj Angad Bawa",
            "Mayank Rawat",
            "Corbin Bosch",
            "Will Jacks",
            "Shardul Thakur",
        ],
        "Bowlers": [
            "Trent Boult",
            "Mayank Markande",
            "Deepak Chahar",
            "Ashwani Kumar",
            "Raghu Sharma",
            "Mohammad Izhar",
            "Allah Ghazanfar",
            "Jasprit Bumrah",
        ],
    },
    "Punjab Kings": {
        "Batters": [
            "Shreyas Iyer",
            "Nehal Wadhera",
            "Vishnu Vinod",
            "Harnoor Pannu",
            "Pyla Avinash",
            "Prabhsimran Singh",
            "Shashank Singh",
        ],
        "All-rounders": [
            "Marcus Stoinis",
            "Harpreet Brar",
            "Marco Jansen",
            "Azmatullah Omarzai",
            "Priyansh Arya",
            "Musheer Khan",
            "Suryansh Shedge",
            "Mitch Owen",
            "Cooper Connolly",
            "Ben Dwarshuis",
        ],
        "Bowlers": [
            "Arshdeep Singh",
            "Yuzvendra Chahal",
            "Vyshak Vijaykumar",
            "Yash Thakur",
            "Xavier Bartlett",
            "Pravin Dubey",
            "Vishal Nishad",
            "Lockie Ferguson",
        ],
    },
    "Rajasthan Royals": {
        "Batters": [
            "Shubham Dubey",
            "Vaibhav Sooryavanshi",
            "Donovan Ferreira",
            "Lhuan-dre Pretorious",
            "Ravi Singh",
            "Aman Rao Perala",
            "Shimron Hetmyer",
            "Yashasvi Jaiswal",
            "Dhruv Jurel",
        ],
        "All-rounders": [
            "Riyan Parag",
            "Yudhvir Singh Charak",
            "Ravindra Jadeja",
            "Dasun Shanaka",
        ],
        "Bowlers": [
            "Jofra Archer",
            "Tushar Deshpande",
            "Kwena Maphaka",
            "Ravi Bishnoi",
            "Sushant Mishra",
            "Yash Raj Punja",
            "Vignesh Puthur",
            "Brijesh Sharma",
            "Adam Milne",
            "Kuldeep Sen",
            "Sandeep Sharma",
            "Nandre Burger",
        ],
    },
    "Royal Challengers Bengaluru": {
        "Batters": [
            "Rajat Patidar",
            "Devdutt Padikkal",
            "Virat Kohli",
            "Phil Salt",
            "Jitesh Sharma",
            "Jordan Cox",
        ],
        "All-rounders": [
            "Krunal Pandya",
            "Swapnil Singh",
            "Tim David",
            "Romario Shepherd",
            "Jacob Bethell",
            "Venkatesh Iyer",
            "Satvik Deswal",
            "Mangesh Yadav",
            "Vicky Ostwal",
            "Vihaan Malhotra",
            "Kanishk Chouhan",
        ],
        "Bowlers": [
            "Josh Hazlewood",
            "Rasikh Dar",
            "Suyash Sharma",
            "Bhuvneshwar Kumar",
            "Nuwan Thushara",
            "Abhinandan Singh",
            "Jacob Duffy",
            "Yash Dayal",
        ],
    },
    "Sunrisers Hyderabad": {
        "Batters": [
            "Ishan Kishan",
            "Aniket Verma",
            "Smaran Ravichandran",
            "Salil Arora",
            "Heinrich Klaasen",
            "Travis Head",
        ],
        "All-rounders": [
            "Harshal Patel",
            "Kamindu Mendis",
            "Harsh Dubey",
            "Shivang Kumar",
            "Krains Fuletra",
            "Liam Livingstone",
            "Abhishek Sharma",
            "Nitish Kumar Reddy",
        ],
        "Bowlers": [
            "Pat Cummins",
            "Zeeshan Ansari",
            "Jaydev Unadkat",
            "Eshan Malinga",
            "Sakib Hussain",
            "Onkar Tarmale",
            "Amit Kumar",
            "Praful Hinge",
            "Shivam Mavi",
            "Dilshan Madushanka",
            "Gerald Coetzee",
        ],
    },
}


CURRENT_TEAM_SOURCES = {
    "Chennai Super Kings": "https://www.iplt20.com/teams/chennai-super-kings",
    "Delhi Capitals": "https://www.iplt20.com/teams/delhi-capitals",
    "Gujarat Titans": "https://www.iplt20.com/teams/gujarat-titans",
    "Kolkata Knight Riders": "https://www.iplt20.com/teams/kolkata-knight-riders",
    "Lucknow Super Giants": "https://www.iplt20.com/teams/lucknow-super-giants",
    "Mumbai Indians": "https://www.iplt20.com/teams/mumbai-indians",
    "Punjab Kings": "https://www.iplt20.com/teams/punjab-kings",
    "Rajasthan Royals": "https://www.iplt20.com/teams/rajasthan-royals",
    "Royal Challengers Bengaluru": "https://www.iplt20.com/teams/royal-challengers-bengaluru",
    "Sunrisers Hyderabad": "https://www.iplt20.com/teams/sunrisers-hyderabad",
}

